### ISSUE TITLE
"Go' on Blyfri 95" fails when parsing

### ISSUE THREAD

**Issue by mm98** [J-Lindvig/Fuelprices_DK#16]
Hi,

There seams to be a problem with parsing `Go' on Blyfri 95` fuel prices (octane 95). The `Go' on` page does exist and seams to have valid content and fuel prices: https://goon.nu/priser/#Aktuellelistepriser

https://github.com/J-Lindvig/Fuelprices_DK/blob/6018094fa93688f76d97ea87ec3cfbaa91901ede/custom_components/fuelprices_dk/fuelprices_dk_api.py#L39-L46

HA log entry (and `Go' on` is  the only one marked as `unavailable`):
```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fuelprices_dk/sensor.py", line 91, in state
    return float(self._fuelCompany.getProductPrice(self._productKey))
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 215, in getProductPrice
    return self._products[productKey]["price"]
KeyError: 'price'
```

Looks like the key `price` doesn't exist for `Go' on Blyfri 95`.
https://github.com/J-Lindvig/Fuelprices_DK/blob/6018094fa93688f76d97ea87ec3cfbaa91901ede/custom_components/fuelprices_dk/fuelprices_dk_api.py#L215

**Comment by J-Lindvig** [comment]
Hello

The prices from Go'on is preferably done with OCR from a image with "pumpepriser". Currently the image is unavailable.

![Screenshot_2023-01-19-16-39-14-799_com android chrome](https://user-images.githubusercontent.com/54498188/213537421-75247937-d34b-4c03-8838-288fb612fe7b.jpg)

It is only on systems without the SSOCR module, we fall back to "listepriser".

I will check the URL later and maybe implement another fallback feature.

Thanks for the posting of the issue.
