### ISSUE TITLE
oil-tankstationer.dk parser failing

### ISSUE THREAD

**Issue by mm98** [J-Lindvig/Fuelprices_DK#22]
Hi,

It looks like `https://www.oil-tankstationer.dk/de-gaeldende-braendstofpriser/` is breaking this integration. Which results in all fuelprices being `unavailable`.

https://github.com/J-Lindvig/Fuelprices_DK/blob/6018094fa93688f76d97ea87ec3cfbaa91901ede/custom_components/fuelprices_dk/fuelprices_dk_parsers.py#L116-L137

```py
2023-08-01 17:40:39.131 ERROR (MainThread) [custom_components.fuelprices_dk.sensor] Unexpected error fetching sensor data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fuelprices_dk/sensor.py", line 39, in async_update_data
    await hass.async_add_executor_job(company.refreshPrices)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 202, in refreshPrices
    self._products = getattr(self._parser, self._key)(self._url, self._products)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_parsers.py", line 135, in oil
    priceSegments[0].text + "." + priceSegments[1].text,
```

**Comment by mm98** [comment]
Fixed in pull request #23

**Comment by JensHKnudsen** [comment]
I had to change **fuelprices_dk_parsers.py** to make OIL work

`
    # OIL!
    def oil(self, url, products):
        r = self._get_website(url)
        div = self._get_html_soup(r).find(id="c9130")
        rows = div.find_all("tr")
        for productKey, productDict in products.items():
            found = False
            for row in rows:
                if found:
                    continue
                cells = row.find_all("td")
                if cells:
                    found = productDict["name"] == cells[0].text
                    if found:
                        products[productKey] = self._addPriceToProduct(
                            productDict,
                            cells[2].text,
                        )
        return products
`
