### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by maxandersen** [J-Lindvig/Fuelprices_DK#5]
All sensors shows up with “unavailable” And I’m getting this in the log: 

```
This error originated from a custom integration.

Logger: custom_components.fuelprices_dk.sensor
Source: custom_components/fuelprices_dk/fuelprices_dk_parsers.py:128 
Integration: Fuelprices DK (documentation, issues) 
First occurred: 11:12:54 AM (1 occurrences) 
Last logged: 11:12:54 AM

Unexpected error fetching sensor data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/fuelprices_dk/sensor.py", line 30, in async_update_data
    await hass.async_add_executor_job(fuelPrices.refresh)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 151, in refresh
    company.refreshPrices()
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 203, in refreshPrices
    self._products = getattr(self._parser, self._key)(self._url, self._products)
  File "/config/custom_components/fuelprices_dk/fuelprices_dk_parsers.py", line 128, in oil
    priceSegments = cells[2].findAll(
IndexError: list index out of range
```

**Comment by J-Lindvig** [comment]
Probably a change in one of the fuelcompanies website. The integration relies heavily on scraping. I will look into the matter asap.

**Comment by J-Lindvig** [comment]
Try with this new version (1.3.1)

**Comment by maxandersen** [comment]
I updated to 1.3.2 and still sees:

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/fuelprices_dk/sensor.py", line 30, in async_update_data
await hass.async_add_executor_job(fuelPrices.refresh)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 151, in refresh
company.refreshPrices()
File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 200, in refreshPrices
self._products = getattr(self._parser, self._key)(self._url, self._products)
File "/config/custom_components/fuelprices_dk/fuelprices_dk_parsers.py", line 130, in oil
priceSegments = cells[2].findAll(
IndexError: list index out of range
```

**Comment by J-Lindvig** [comment]
What is your hardware setup, is it a docker environment?/Jacob 5. sep. 2022 12.56 skrev Max Rydahl Andersen ***@***.***>:
I updated to 1.3.2 and still sees:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/fuelprices_dk/sensor.py", line 30, in async_update_data
await hass.async_add_executor_job(fuelPrices.refresh)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 151, in refresh
company.refreshPrices()
File "/config/custom_components/fuelprices_dk/fuelprices_dk_api.py", line 200, in refreshPrices
self._products = getattr(self._parser, self._key)(self._url, self._products)
File "/config/custom_components/fuelprices_dk/fuelprices_dk_parsers.py", line 130, in oil
priceSegments = cells[2].findAll(
IndexError: list index out of range
